### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by thany** [curasystems/jxrlib#3]
Please release binaries 🙏

I'm sure you (author) tests whether the source code can build or not, so why not make the result of that available to everyone? I personally don't have build tools on my pc, just like many other people who just need this lib as a plugin for something.

**Comment by matthiasg** [comment]
@thany this is just a clone for code safety reasons. We are not the author and the original is located at https://jxrlib.codeplex.com/.

**Comment by MarcusJohnson91** [comment]
Codeplex is dead...

**Comment by matthiasg** [comment]
That may be so, but we did not write the code nor do we have a binary to distribute so I closed the issue

**Comment by thany** [comment]
I see. Even so, I was hoping you could still release binaries. If, of course, you have the means to produce them.

**Comment by matthiasg** [comment]
We did not produce binaries so no. We only wanted to look at some internals of the code and kept it for reference
